---
apiVersion: v1
kind: Secret
metadata:
  name: apacheds-ldif
  namespace: apacheds
type: Opaque
stringData:
  data.ldif: |-
    dn: OU=Users,DC=apacheds,DC=ojkastl,DC=de
    objectClass: organizationalUnit
    ou: users

    dn: OU=Groups,DC=apacheds,DC=ojkastl,DC=de
    objectClass: organizationalUnit
    ou: Groups

    dn: CN=hpotter,OU=Users,DC=apacheds,DC=ojkastl,DC=de
    objectClass: user
    cn: hpotter
    givenName: Harry
    sn: Potter
    samAccountName: hpotter
    mail: hpotter@hogwarts.invalid
    title: Tester
    telephoneNumber: 123-456-7890
    userPassword: b1s

    dn: CN=hgranger,OU=Users,DC=apacheds,DC=ojkastl,DC=de
    objectClass: user
    cn: hgranger
    givenName: Hermione
    sn: Granger
    samAccountName: hgranger
    mail: hgranger@hogwarts.invalid
    title: Tester
    telephoneNumber: 123-456-7890
    userPassword: b1s

    dn: CN=rweasley,OU=Users,DC=apacheds,DC=ojkastl,DC=de
    objectClass: user
    cn: rweasley
    givenName: Ron
    sn: Weasley
    samAccountName: rweasley
    mail: rweasley@hogwarts.invalid
    title: Tester
    telephoneNumber: 123-456-7890
    userPassword: b1s

    dn: CN=k8s-cluster-admins,OU=Groups,DC=apacheds,DC=ojkastl,DC=de
    objectClass: group
    cn: k8s-cluster-admins
    member: CN=hpotter,OU=Users,DC=apacheds,DC=ojkastl,DC=de

    dn: CN=group2,OU=Groups,DC=apacheds,DC=ojkastl,DC=de
    objectClass: group
    cn: group2
    member: CN=hpotter,OU=Users,DC=apacheds,DC=ojkastl,DC=de

    dn: CN=k8s-create-ns,OU=Groups,DC=apacheds,DC=ojkastl,DC=de
    objectClass: group
    cn: k8s-create-ns
    member: CN=hgranger,OU=Users,DC=apacheds,DC=ojkastl,DC=de
